layout_spectrum: 0.29278897517360747
typography_spectrum: 0.15781447989866138
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.3298892572056502
  lightness: 0.7755025352817029
  saturation: 0.3095340661238879
  rhythmicContrast: 0.9407417988404632
name: thehumanweb
favicon: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75042725-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
