analytics:
  google: UA-75042725-1
color:
  brandColors:
    - '#ffffff'
    - '#161616'
    - '#654f1d'
    - '#ad5995'
    - '#d7b0ca'
  brandStrength: 0.5625
  lightness: 0.991638
  rhythmicContrast: 0.52661
  saturation: 0.14692
cta: {}
layout_spectrum: 0.74593
name: thehumanweb
opengraph: {}
purpose: []
typography_spectrum: 0.1597323624882847
