name: thehumanweb
favicon: null
layout_spectrum: 0.25949
typography_spectrum: 0.1597323624882847
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75042725-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e3cba9'
    - '#5b5964'
    - '#aa6858'
    - '#bb9b75'
    - '#262431'
  brandStrength: 0.5
  lightness: 0.991638
  saturation: 0.14692
  rhythmicContrast: 0.52661
purpose: []
