name: thehumanweb
favicon: null
layout_spectrum: 0.74593
typography_spectrum: 0.1597323624882847
title: thehumanweb
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75042725-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#161616'
    - '#654f1d'
    - '#ad5995'
    - '#d7b0ca'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.14692006399855018
  rhythmicContrast: 0.526610691100359
purpose: []
