name: the-human-web
favicon: null
layout_spectrum: 0.2366365164052695
typography_spectrum: 0.1597323624882847
title: the-human-web
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7940718494355679
  lightness: 0.037824405590072274
  saturation: 0.14692006399855018
  rhythmicContrast: 0.526610691100359
purpose: []
